### ISSUE TITLE
Hardhat and Truffle output different contract sizes

### ISSUE THREAD

**Issue by mattfixme** [ItsNickBarry/hardhat-contract-sizer#18]
I can deploy contract using Truffle, but not Hardhat. i don't know which one is true.

**it's truffle output**
![Xnip2022-03-18_12-11-29](https://user-images.githubusercontent.com/94779860/158936744-4f05774f-4ca3-4866-9790-0f170e36ab22.jpg)

**it's Hardhat output**
![Xnip2022-03-18_12-13-33](https://user-images.githubusercontent.com/94779860/158936754-68464828-d111-4826-9ff4-efc5a1d4463c.jpg)

**Comment by ItsNickBarry** [comment]
Check compiler settings, particularly optimizer runs.  Because this is a Hardhat plugin, it has been tested only with compilation via Hardhat.

Hardhat configuration example: https://github.com/solidstate-network/solidstate-solidity/blob/18744f757fcdf8d9e65803d2723a66b1a1c0461d/hardhat.config.ts#L16-L20
